text1 = input('Type something, and Ill tell you what type of data it is:')
print('The primitive type is', type(text1))
print('Is it a number?', text1.isnumeric())
print('Is it upper case?', text1.isupper())
print('Is it capitalized?', text1.istitle())
print('Is it lower case?', text1.islower())
print('Is it a alpha numeric?', text1.isalnum())
print('Is it a decimal number?', text1.isdecimal())
print('Is it a digit?', text1.isdigit())
print('Is it a space?', text1.isspace())
print('Is it an ASCII character?', text1.isascii())
print('Is it printable?', text1.isprintable())
